---
apiVersion: v1
kind: ConfigMap
metadata:
  name: galactus
data:
  ACTIVITY_TYPE: serviceAccountLastAuthentication
  # enable debug logging
  DEBUG: '1'
  GCP_PROJECT: $GCP_PROJECT
  THRESHOLD: '2022-01-01T00:00:00Z'
