apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: galactus

commonLabels:
  app: galactus

images:
  - name: galactus
    newName: $IMAGE_NAME
    newTag: latest

resources:
  - configmap.yaml
  - cronjob.yaml
  - namespace.yaml
  - serviceaccount.yaml
