apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: galactus

commonLabels:
  app: galactus

images:
  - name: galactus
    newName: my-registry/my-postgres
    newTag: v1

resources:
  - configmap.yaml
  - cronjob.yaml
  - serviceaccount.yaml
